version: '3.3'
services:
  angular-app: 
    container_name: angular-app-service
    restart: always
    build:
      context: ./all-service
      dockerfile: ./angular-app/Dockerfile
    ports:
      - '4200:80'
    links: 
      - mongo
  node-app: 
    container_name: node-app-service
    restart: always
    build:
      context: ./all-service
      dockerfile: ./node-app/Dockerfile
    ports:
      - '3000:3000'
    links: 
      - mongo
  mongo:
    container_name: mongo-app-service
    image: mongo
    ports:
      - '27017:27017'
  

